version: '3.8'

services:
  yolo-microservice:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - yolo-network
    # The YOLO microservice is the main service that performs object detection operations.

  redis:
    image: "redis:alpine"
    networks:
      - yolo-network
    #The Redis service is used for fast data access and caching operations for the YOLO microservice.

networks:
  yolo-network:
    driver: bridge
    # A private network providing an isolated network between microservices.